//export {default as Reversi} from "./Reversi-Module"
export {default as TicTacToe} from "./TicTacToe-Module"
//export {default as Dices} from "./Poker-Module"
export {default as Poker} from "./Poker-Module"
export {default as RoPaSci} from "./RoPaSci-Module"